application: pynotes123
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /js
  static_dir: static/js
  expiration: 10000d

- url: /static
  static_dir: static

- url: /.*
  script: index.py
  login: admin

