from web.template import CompiledTemplate, ForLoop, TemplateResult


# coding: utf-8
def index (notes):
    __lineoffset__ = -4
    loop = ForLoop()
    self = TemplateResult(); extend_ = self.extend
    extend_([u'\n'])
    extend_([u'<html>\n'])
    extend_([u'  <head>\n'])
    extend_([u'    <!--Load the AJAX API-->\n'])
    extend_([u'    <script type="text/javascript" src="https://www.google.com/jsapi"></script>\n'])
    extend_([u'    <script type="text/javascript">\n'])
    extend_([u'    \n'])
    extend_([u'      // Load the Visualization API and the piechart package.\n'])
    extend_([u'        google.load("visualization", "1", {packages:["corechart"]});\n'])
    extend_([u'      \n'])
    extend_([u'      // Set a callback to run when the Google Visualization API is loaded.\n'])
    extend_([u'      google.setOnLoadCallback(drawChart);\n'])
    extend_([u'\n'])
    extend_([u'\n'])
    extend_([u'      // Callback that creates and populates a data table, \n'])
    extend_([u'      // instantiates the pie chart, passes in the data and\n'])
    extend_([u'      // draws it.\n'])
    extend_([u'      function drawChart() {\n'])
    extend_([u'                // Create and populate the data table.\n'])
    extend_([u'                var data = new google.visualization.DataTable();\n'])
    extend_([u'                var totalNum=', escape_(notes.count(), True), u';\n'])
    extend_([u'                var actualDate=new Array(10);\n'])
    extend_([u'                var expectedDate=new Array(10);\n'])
    extend_([u'                var index=0;\n'])
    extend_([u'                        \n'])
    for note in loop.setup(notes):
        extend_(['                ', u'    actualDate[index]=new Date(', escape_(note.actualDate.year, True), u',', escape_(note.actualDate.month, True), u',', escape_(note.actualDate.day, True), u');\n'])
        extend_(['                ', u'    expectedDate[index]=new Date(', escape_(note.expectedDate.year, True), u',', escape_(note.expectedDate.month, True), u',', escape_(note.expectedDate.day, True), u');\n'])
        extend_(['                ', u'    actualDate[index].setMonth(actualDate[index].getMonth()-1);\n'])
        extend_(['                ', u'    expectedDate[index].setMonth(expectedDate[index].getMonth()-1);\n'])
        extend_(['                ', u'    index=index+1;\n'])
    extend_([u'                var raw_data=new Array();\n'])
    extend_([u'                raw_data[0]=new Array();\n'])
    extend_([u"                raw_data[0][0]='Gap';\n"])
    extend_([u'                raw_data[1]=new Array();\n'])
    extend_([u"                raw_data[1][0]='Bias';\n"])
    extend_([u'                for(var i=1;i<index;++i)\n'])
    extend_([u'                {\n'])
    extend_([u'                        raw_data[0][i]=parseInt(Math.abs(actualDate[i]-actualDate[i-1])/1000/60/60/24);\n'])
    extend_([u'                        raw_data[1][i]=parseInt(Math.abs(expectedDate[i]-actualDate[i-1])/1000/60/60/24);\n'])
    extend_([u'                }\n'])
    extend_([u'  \n'])
    extend_([u'                var years = new Array();\n'])
    extend_([u'                for(var i=1;i<index;++i)\n'])
    extend_([u'                {\n'])
    extend_([u'                        var month=actualDate[i].getMonth()+1;\n'])
    extend_([u"                        years[i-1]=actualDate[i].getFullYear()+'-'+month+'-'+actualDate[i].getDate();\n"])
    extend_([u'                }\n'])
    extend_([u'                  \n'])
    extend_([u"                data.addColumn('string', 'Date');\n"])
    extend_([u'  for (var i = 0; i  < raw_data.length; ++i) {\n'])
    extend_([u"    data.addColumn('number', raw_data[i][0]);    \n"])
    extend_([u'  }\n'])
    extend_([u'  \n'])
    extend_([u'  data.addRows(years.length);\n'])
    extend_([u'\n'])
    extend_([u'  for (var j = 0; j < years.length; ++j) {    \n'])
    extend_([u'    data.setValue(j, 0, years[j].toString());    \n'])
    extend_([u'  }\n'])
    extend_([u'  for (var i = 0; i  < raw_data.length; ++i) {\n'])
    extend_([u'    for (var j = 1; j  < raw_data[i].length; ++j) {\n'])
    extend_([u'      data.setValue(j-1, i+1, raw_data[i][j]);    \n'])
    extend_([u'    }\n'])
    extend_([u'  }\n'])
    extend_([u'  var stepLen=100;\n'])
    extend_([u'  // Create and draw the visualization.\n'])
    extend_([u"  new google.visualization.ColumnChart(document.getElementById('chart_div')).\n"])
    extend_([u'      draw(data,\n'])
    extend_([u'           {title:"ISee", \n'])
    extend_([u'            width:stepLen*index, height:400,\n'])
    extend_([u'            hAxis: {title: "Date"}}\n'])
    extend_([u'      );\n'])
    extend_([u'    }\n'])
    extend_([u'    </script>\n'])
    extend_([u'  </head>\n'])
    extend_([u'<table border="0" width="100%" cellpadding="10">\n'])
    extend_([u'<tr>\n'])
    extend_([u'<td width="40%" valign="top">\n'])
    extend_([u'<h1>The Rhapsody of Life</h1>\n'])
    extend_([u'<h2>last 10 times</h2>\n'])
    extend_([u'\n'])
    for note in loop.setup(notes):
        extend_([u'<p>', escape_(note.actualDate, True), u' <span style="color: red">', escape_(note.expectedDate, True), u'</span></p>\n'])
        extend_([u'\n'])
    extend_([u'<h2>add a date</h2>\n'])
    extend_([u'<form method="post" action="/note">\n'])
    extend_([u'<p>Year  \n'])
    extend_([u'<select name="year" size="1" id="year">\n'])
    for i in loop.setup(range(2013,2023)):
        extend_([' ', u'   <option value=', escape_(i, True), u'>', escape_(i, True), u'</option>\n'])
    extend_([u'</select> \n'])
    extend_([u'Month \n'])
    extend_([u'<select name="month" size="1" id="month">\n'])
    for i in loop.setup(range(1,13)):
        extend_([' ', u'   <option value=', escape_(i, True), u'>', escape_(i, True), u'</option>\n'])
    extend_([u'</select>\n'])
    extend_([u'\n'])
    extend_([u'Date \n'])
    extend_([u'<select name="day" size="1" id="day">\n'])
    for i in loop.setup(range(1,32)):
        extend_([' ', u'   <option value=', escape_(i, True), u'>', escape_(i, True), u'</option>\n'])
    extend_([u'</select> \n'])
    extend_([u'<button type="submit">submit</button>\n'])
    extend_([u'</p>\n'])
    extend_([u'<h2>about this site</h2>\n'])
    extend_([u'\n'])
    extend_([u'<p>It\'s a website specially for U. <a href="/source">View the source.</a></p>\n'])
    extend_([u'\n'])
    extend_([u'<address>\n'])
    extend_([u'  <a href="http://hi.baidu.com/kamelzcs/">Kamel</a> all rights reserved since 2011.\n'])
    extend_([u'</address>\n'])
    extend_([u'</td>\n'])
    extend_([u'\n'])
    extend_([u'<td width="60%" valign="top">\n'])
    extend_([u'  <body>\n'])
    extend_([u'<!--Div that will hold the pie chart-->\n'])
    extend_([u'    <div id="chart_div" style="width:400; height:300"></div>\n'])
    extend_([u'  </body>\n'])
    extend_([u'</td>\n'])
    extend_([u'\n'])
    extend_([u'</tr>\n'])
    extend_([u'</table>\n'])
    extend_([u'\n'])
    extend_([u'  \n'])
    extend_([u'  \n'])
    extend_([u'</html>\n'])

    return self

index = CompiledTemplate(index, 'templates/index.html')
join_ = index._join; escape_ = index._escape

# coding: utf-8
def indexLast (notes):
    __lineoffset__ = -4
    loop = ForLoop()
    self = TemplateResult(); extend_ = self.extend
    extend_([u'<h1>The Rhapsody of Life</h1>\n'])
    extend_([u'\n'])
    extend_([u'<h2>last 10 times</h2>\n'])
    extend_([u'\n'])
    for note in loop.setup(notes):
        extend_([u'<p>', escape_(note.actualDate, True), u' <span style="color: red">', escape_(note.expectedDate, True), u'</span></p>\n'])
        extend_([u'\n'])
    extend_([u'<h2>add a date</h2>\n'])
    extend_([u'<form method="post" action="/note">\n'])
    extend_([u'<p>Year  \n'])
    extend_([u'<select name="year" size="1" id="year">\n'])
    for i in loop.setup(range(2011,2013)):
        extend_([' ', u'   <option value=', escape_(i, True), u'>', escape_(i, True), u'</option>\n'])
    extend_([u'</select> \n'])
    extend_([u'Month \n'])
    extend_([u'<select name="month" size="1" id="month">\n'])
    for i in loop.setup(range(1,13)):
        extend_([' ', u'   <option value=', escape_(i, True), u'>', escape_(i, True), u'</option>\n'])
    extend_([u'</select>\n'])
    extend_([u'\n'])
    extend_([u'Date \n'])
    extend_([u'<select name="day" size="1" id="day">\n'])
    for i in loop.setup(range(1,32)):
        extend_([' ', u'   <option value=', escape_(i, True), u'>', escape_(i, True), u'</option>\n'])
    extend_([u'</select> \n'])
    extend_([u'<button type="submit">submit</button>\n'])
    extend_([u'</p>\n'])
    extend_([u'<h2>about this site</h2>\n'])
    extend_([u'\n'])
    extend_([u'<p>It\'s a website specially for U. <a href="/source">View the source.</a></p>\n'])
    extend_([u'\n'])
    extend_([u'<address>\n'])
    extend_([u'  <a href="http://hi.baidu.com/kamelzcs/">Kamel</a> all rights reserved since 2011.\n'])
    extend_([u'</address>\n'])

    return self

indexLast = CompiledTemplate(indexLast, 'templates/indexLast.html')
join_ = indexLast._join; escape_ = indexLast._escape

